# Generated by Django 5.1.5 on 2025-01-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deadline_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False)),
                ('tags', models.ManyToManyField(related_name='tasks', to='app.tag')),
            ],
            options={
                'ordering': ('is_completed', 'datetime'),
            },
        ),
    ]
